using System.Collections.Generic;

namespace GanglandUndercover.Core
{
    public static class Localization
    {
        private static readonly Dictionary<string, string> Chinese = new Dictionary<string, string>
        {
            { "game.title", "黑街卧底" },
            { "role.choose", "选择你在港口区的身份" },
            { "role.Gang", "黑帮" },
            { "role.Police", "警察" },
            { "role.Undercover", "卧底" },
            { "phase.RoleSelect", "选择身份" },
            { "phase.PlayerTurn", "玩家回合" },
            { "phase.AiTurn", "对手回合" },
            { "phase.GameOver", "游戏结束" },
            { "button.restart", "重新开始" },
            { "button.language", "语言: 中文" },
            { "label.role", "身份" },
            { "label.day", "第几天" },
            { "label.evidence", "证据" },
            { "label.policeHeat", "警力热度" },
            { "label.shipment", "货运进度" },
            { "label.cover", "掩护" },
            { "label.suspicion", "怀疑值" },
            { "label.publicTrust", "民众信任" },
            { "label.gangDistricts", "黑帮区域" },
            { "label.policeDistricts", "警方区域" },
            { "label.contested", "争夺区域" },
            { "label.control", "控制方" },
            { "label.witness", "证人" },
            { "label.lockdown", "封锁" },
            { "short.gang", "黑" },
            { "short.police", "警" },
            { "district.Dockyard", "码头" },
            { "district.WarehouseRow", "仓库街" },
            { "district.NightMarket", "夜市" },
            { "district.PolicePrecinct", "警局" },
            { "district.Clinic", "诊所" },
            { "district.TenementBlock", "公寓楼" },
            { "action.gang_expand.label", "扩张地盘" },
            { "action.gang_expand.desc", "提升所选区域的黑帮控制。" },
            { "action.gang_ship.label", "转运货物" },
            { "action.gang_ship.desc", "推进大货运，但会引来警方注意。" },
            { "action.gang_silence.label", "威压证人" },
            { "action.gang_silence.desc", "移除证人并损害民众信任。" },
            { "action.gang_bribe.label", "买通卡点" },
            { "action.gang_bribe.desc", "解除封锁并削弱警力。" },
            { "action.police_investigate.label", "调查取证" },
            { "action.police_investigate.desc", "从所选区域收集证据。" },
            { "action.police_raid.label", "突击搜查" },
            { "action.police_raid.desc", "削弱黑帮影响，但会损害民众信任。" },
            { "action.police_protect.label", "保护证人" },
            { "action.police_protect.desc", "保护证人并提高民众信任。" },
            { "action.police_lockdown.label", "设置卡点" },
            { "action.police_lockdown.desc", "封锁区域，干扰黑帮转运。" },
            { "action.undercover_cover.label", "维持掩护" },
            { "action.undercover_cover.desc", "表现忠诚，降低怀疑并维持身份。" },
            { "action.undercover_intel.label", "传递情报" },
            { "action.undercover_intel.desc", "获得证据，但提高暴露风险。" },
            { "action.undercover_sabotage.label", "破坏货运" },
            { "action.undercover_sabotage.desc", "拖慢黑帮货运，但风险很高。" },
            { "action.undercover_dead_drop.label", "秘密投递" },
            { "action.undercover_dead_drop.desc", "暗中传递证据，不直接升高警力热度。" },

            // ─── M5-M8 新增：小游戏 / 会议 / 监控 / Bot / 职业系统 ───
            { "task.scan", "扫描" },
            { "task.wiring", "接线" },
            { "task.calibrate", "校准" },
            { "task.diversion", "破译" },
            { "task.upload", "上传" },
            { "task.report", "报告" },
            { "task.repair", "修复" },
            { "task.clean", "清理" },
            { "task.inspect", "查验" },
            { "task.sabotage", "破坏" },
            { "task.generic", "通用任务" },
            { "minigame.charge", "按住扫描" },
            { "minigame.step", "步骤" },
            { "minigame.exit", "退出" },
            { "minigame.key.1", "键 1" },
            { "minigame.key.2", "键 2" },
            { "minigame.key.3", "键 3" },
            { "minigame.feedback.pass", "校验通过" },
            { "minigame.feedback.fail", "输入不匹配" },
            { "minigame.feedback.hint", "按顺序校验，再按住扫描推进现场结果" },
            { "meeting.title", "九龙港城会议" },
            { "meeting.discuss", "讨论" },
            { "meeting.vote", "投票" },
            { "meeting.reason", "会议原因：" },
            { "meeting.evidence", "证据墙：" },
            { "meeting.tally", "票型：" },
            { "meeting.voice", "语音：" },
            { "meeting.outcome", "上轮结论：" },
            { "meeting.vote.panel", "投票面板" },
            { "meeting.vote.skip", "跳过投票" },
            { "meeting.seat.round", "会议圆桌" },
            { "meeting.seat.evidence", "证据墙" },
            { "meeting.seat.voice", "语音全员" },
            { "status.ejected", "出局" },
            { "status.alive", "存活" },
            { "role.gang", "黑帮" },
            { "role.police", "警察" },
            { "role.undercover", "卧底" },
            { "role.mole", "内鬼" },
            { "profession.inspector", "警探" },
            { "profession.forensics", "法医" },
            { "profession.tech", "技术员" },
            { "profession.enforcer", "打手" },
            { "profession.fixer", "清道夫" },
            { "profession.undercover_agent", "卧底" },
            { "profession.mole", "内鬼" },
            { "profession.driver", "车手" },
            { "map.title", "九龙港区战术地图" },
            { "map.legend", "黄: 玩家 | 青: 任务 | 橙框: 垂直切片核心区 | 红: 破坏/尸体 | 灰: 出局 | M 收起" },
            { "map.marker.player", "你" },
            { "map.marker.corpse", "尸" },
            { "map.mode.harbour", "港区地图" },
            { "map.mode.police", "警署地图" },
            { "map.VerticalSlice.core", "集合" },
            { "map.VerticalSlice.ctv", "监控" },
            { "map.VerticalSlice.cafe", "茶餐厅" },
            { "map.VerticalSlice.market", "夜市" },
            { "map.VerticalSlice.alley", "后巷" },
            { "map.VerticalSlice.power", "电房" },
            { "result.title", "行动结算" },
            { "result.resume", "重开同房间" },
            { "result.return_lobby", "返回房间" },
            { "hud.compact.hint", "WASD 移动 | E 互动 | Q 击倒 | R 报案/紧急 | F 技能 | M 大地图 | I 案情板" },
            { "action.interact", "E 互动" },
            { "action.kill", "Q 击倒" },
            { "action.report", "R 报案" },
            { "action.ability", "F 技能" },
            { "action.vent", "V 通风管" },
            { "action.map", "M 大地图" },
            { "action.intel", "I 案情板" },
            { "action.interact.ready", "[E] 查证" },
            { "action.interact.na", "[E] -" },
            { "action.kill.ready", "[Q] 击倒" },
            { "action.kill.na", "[Q] -" },
            { "action.report.ready", "[R] 报案" },
            { "action.report.na", "[R] -" },
            { "action.ability.ready", "[F] 技能" },
            { "action.ability.na", "[F] -" },
            { "ability.body_drag", "拖尸" },
            { "ability.dark_vision", "夜视" },
            { "ability.remote_surveillance", "远程监控" },
            { "ability.footprint_track", "足迹追踪" },
            { "notify.corpse_found", "尸体被发现" },
            { "notify.sabotage", "破坏事件" },
            { "notify.emergency", "紧急会议" },
            { "notify.blackout", "断电" },
            { "notify.lockdown", "区域封锁" },

            // ─── F1-F4 体验内容 + 可访问性 ───
            { "tutorial.replay", "教程回顾" },
            { "tutorial.skip", "跳过教程" },
            { "tutorial.welcome", "欢迎来到九龙港城" },
            { "setting.volume_bgm", "背景音乐" },
            { "setting.window_mode", "窗口模式" },
            { "setting.resolution", "分辨率" },
            { "room.copy_code", "复制房间码" },
            { "room.ready", "准备" },
            { "room.cancel_ready", "取消准备" },
            { "room.leave_confirm", "确定离开？对局进度将丢失。" },
            { "a11y.colorblind_mode", "色盲模式" },
            { "a11y.faction_police", "警蓝" },
            { "a11y.faction_gang", "匪红" },
            { "a11y.faction_undercover", "卧绿" },
            { "a11y.faction_mole", "内黄" },
            { "a11y.sabotage_blackout", "⚡停电" },
            { "a11y.sabotage_lockdown", "🔒封锁" },
            { "a11y.sabotage_comms", "📡断讯" }
        };

        private static readonly Dictionary<string, string> English = new Dictionary<string, string>
        {
            { "game.title", "Gangland Undercover" },
            { "role.choose", "Choose your role in the Port District" },
            { "role.Gang", "Gang" },
            { "role.Police", "Police" },
            { "role.Undercover", "Undercover" },
            { "phase.RoleSelect", "Role Select" },
            { "phase.PlayerTurn", "Player Turn" },
            { "phase.AiTurn", "AI Turn" },
            { "phase.GameOver", "Game Over" },
            { "button.restart", "Restart" },
            { "button.language", "Language: English" },
            { "label.role", "Role" },
            { "label.day", "Day" },
            { "label.evidence", "Evidence" },
            { "label.policeHeat", "Police Heat" },
            { "label.shipment", "Shipment" },
            { "label.cover", "Cover" },
            { "label.suspicion", "Suspicion" },
            { "label.publicTrust", "Public Trust" },
            { "label.gangDistricts", "Gang Districts" },
            { "label.policeDistricts", "Police Districts" },
            { "label.contested", "Contested" },
            { "label.control", "Control" },
            { "label.witness", "Witness" },
            { "label.lockdown", "Lockdown" },
            { "short.gang", "G" },
            { "short.police", "P" },
            { "district.Dockyard", "Dockyard" },
            { "district.WarehouseRow", "Warehouse Row" },
            { "district.NightMarket", "Night Market" },
            { "district.PolicePrecinct", "Police Precinct" },
            { "district.Clinic", "Clinic" },
            { "district.TenementBlock", "Tenement Block" },
            { "action.gang_expand.label", "Expand Turf" },
            { "action.gang_expand.desc", "Increase gang control in the selected district." },
            { "action.gang_ship.label", "Move Shipment" },
            { "action.gang_ship.desc", "Advance the major shipment, but increase police attention." },
            { "action.gang_silence.label", "Pressure Witness" },
            { "action.gang_silence.desc", "Remove a witness and damage public trust." },
            { "action.gang_bribe.label", "Bribe Checkpoint" },
            { "action.gang_bribe.desc", "Clear lockdown and weaken police presence." },
            { "action.police_investigate.label", "Investigate" },
            { "action.police_investigate.desc", "Collect evidence from the selected district." },
            { "action.police_raid.label", "Raid" },
            { "action.police_raid.desc", "Reduce gang influence, but risk public trust." },
            { "action.police_protect.label", "Protect Witness" },
            { "action.police_protect.desc", "Secure a witness and improve public trust." },
            { "action.police_lockdown.label", "Set Checkpoint" },
            { "action.police_lockdown.desc", "Lock down a district to disrupt gang movement." },
            { "action.undercover_cover.label", "Maintain Cover" },
            { "action.undercover_cover.desc", "Act loyal to reduce suspicion and preserve cover." },
            { "action.undercover_intel.label", "Pass Intel" },
            { "action.undercover_intel.desc", "Gain evidence while risking suspicion." },
            { "action.undercover_sabotage.label", "Sabotage Shipment" },
            { "action.undercover_sabotage.desc", "Slow the gang and risk exposure." },
            { "action.undercover_dead_drop.label", "Dead Drop" },
            { "action.undercover_dead_drop.desc", "Build evidence without open police heat." },

            // ─── M5-M8 New: Minigames / Meeting / Surveillance / Bot / Profession ───
            { "task.scan", "Scan" },
            { "task.wiring", "Wiring" },
            { "task.calibrate", "Calibrate" },
            { "task.diversion", "Diversion" },
            { "task.upload", "Upload" },
            { "task.report", "Report" },
            { "task.repair", "Repair" },
            { "task.clean", "Clean" },
            { "task.inspect", "Inspect" },
            { "task.sabotage", "Sabotage" },
            { "task.generic", "Generic Task" },
            { "minigame.charge", "Hold to Scan" },
            { "minigame.step", "Step" },
            { "minigame.exit", "Exit" },
            { "minigame.key.1", "Key 1" },
            { "minigame.key.2", "Key 2" },
            { "minigame.key.3", "Key 3" },
            { "minigame.feedback.pass", "Verified" },
            { "minigame.feedback.fail", "Input mismatch" },
            { "minigame.feedback.hint", "Follow the sequence, then hold scan to submit." },
            { "meeting.title", "Kowloon Port Meeting" },
            { "meeting.discuss", "Discussion" },
            { "meeting.vote", "Voting" },
            { "meeting.reason", "Reason: " },
            { "meeting.evidence", "Evidence: " },
            { "meeting.tally", "Vote tally: " },
            { "meeting.voice", "Voice: " },
            { "meeting.outcome", "Last outcome: " },
            { "meeting.vote.panel", "Vote Panel" },
            { "meeting.vote.skip", "Skip Vote" },
            { "meeting.seat.round", "Round Table" },
            { "meeting.seat.evidence", "Evidence Wall" },
            { "meeting.seat.voice", "Voice Channel" },
            { "status.ejected", "Ejected" },
            { "status.alive", "Alive" },
            { "role.gang", "Gang" },
            { "role.police", "Police" },
            { "role.undercover", "Undercover" },
            { "role.mole", "Mole" },
            { "profession.inspector", "Inspector" },
            { "profession.forensics", "Forensics" },
            { "profession.tech", "Tech" },
            { "profession.enforcer", "Enforcer" },
            { "profession.fixer", "Fixer" },
            { "profession.undercover_agent", "Undercover Agent" },
            { "profession.mole", "Mole" },
            { "profession.driver", "Driver" },
            { "map.title", "Kowloon Port Tactical Map" },
            { "map.legend", "Yel: Player | Cyan: Task | Org outline: VSlice core | Red: Sabotage/Corpse | Gray: Out | M toggle" },
            { "map.marker.player", "You" },
            { "map.marker.corpse", "X" },
            { "map.mode.harbour", "Harbour Map" },
            { "map.mode.police", "Police Station Map" },
            { "map.VerticalSlice.core", "Assembly" },
            { "map.VerticalSlice.ctv", "CCTV" },
            { "map.VerticalSlice.cafe", "Cafe" },
            { "map.VerticalSlice.market", "Night Market" },
            { "map.VerticalSlice.alley", "Back Alley" },
            { "map.VerticalSlice.power", "Power Room" },
            { "result.title", "Match Result" },
            { "result.resume", "Replay Same Room" },
            { "result.return_lobby", "Return to Lobby" },
            { "hud.compact.hint", "WASD Move | E Interact | Q Kill | R Report/Emergency | F Ability | M Map | I Intel" },
            { "action.interact", "E Interact" },
            { "action.kill", "Q Kill" },
            { "action.report", "R Report" },
            { "action.ability", "F Ability" },
            { "action.vent", "V Vent" },
            { "action.map", "M Map" },
            { "action.intel", "I Intel" },
            { "action.interact.ready", "[E] Inspect" },
            { "action.interact.na", "[E] -" },
            { "action.kill.ready", "[Q] Kill" },
            { "action.kill.na", "[Q] -" },
            { "action.report.ready", "[R] Report" },
            { "action.report.na", "[R] -" },
            { "action.ability.ready", "[F] Ability" },
            { "action.ability.na", "[F] -" },
            { "ability.body_drag", "Drag" },
            { "ability.dark_vision", "Night Vision" },
            { "ability.remote_surveillance", "Remote Surveillance" },
            { "ability.footprint_track", "Footprint Track" },
            { "notify.corpse_found", "Corpse found" },
            { "notify.sabotage", "Sabotage" },
            { "notify.emergency", "Emergency Meeting" },
            { "notify.blackout", "Blackout" },
            { "notify.lockdown", "Lockdown" },

            // ─── F1-F4 Experience Content + Accessibility ───
            { "tutorial.replay", "Replay Tutorial" },
            { "tutorial.skip", "Skip Tutorial" },
            { "tutorial.welcome", "Welcome to Kowloon Port" },
            { "setting.volume_bgm", "Background Music" },
            { "setting.window_mode", "Window Mode" },
            { "setting.resolution", "Resolution" },
            { "room.copy_code", "Copy Room Code" },
            { "room.ready", "Ready" },
            { "room.cancel_ready", "Cancel Ready" },
            { "room.leave_confirm", "Leave? Match progress will be lost." },
            { "a11y.colorblind_mode", "Colorblind Mode" },
            { "a11y.faction_police", "Police" },
            { "a11y.faction_gang", "Gang" },
            { "a11y.faction_undercover", "UC" },
            { "a11y.faction_mole", "Mole" },
            { "a11y.sabotage_blackout", "⚡ Blackout" },
            { "a11y.sabotage_lockdown", "🔒 Lockdown" },
            { "a11y.sabotage_comms", "📡 Comms Down" }
        };

        /// <summary>当前语言，默认中文</summary>
        public static GameLanguage CurrentLanguage { get; set; } = GameLanguage.Chinese;

        /// <summary>快捷方法：使用当前语言查询文本</summary>
        public static string T(string key) => Text(CurrentLanguage, key);

        public static string Text(GameLanguage language, string key)
        {
            Dictionary<string, string> table = language == GameLanguage.Chinese ? Chinese : English;

            if (table.TryGetValue(key, out string value))
            {
                return value;
            }

            return key;
        }
    }
}
